### ISSUE TITLE
The structure of passwords file in the root folder

### ISSUE THREAD

**Issue by misnuge** [interledger/connector.land#11]
It would be helpful if you briefly explain about the structure of passwords file because the file is missing.  Thanks again.

**Comment by michielbdejong** [comment]
It's going to change to use environment variables. Sorry for not noticing this issue earlier!

To answer your question, passwords.js was used when connector.land still connected to each node's ledger. Now peering is used, and the current filename is `data/creds.json`, and its structure is like this:
```json
{
  "keypair": {
    "priv": "...",
    "pub": "..."
  }
}
```

**Comment by michielbdejong** [comment]
Follow https://github.com/interledger/connector.land/issues/19 for further updates
