### ISSUE TITLE
avoid using statics from cdn.rawgit.com

### ISSUE THREAD

**Issue by michielbdejong** [interledger/connector.land#18]
It's incompatible with PrivacyBadger

**Comment by dappelt** [comment]
PrivacyBadger blocks by default content loaded from `cdn.rawgit.com`, which prevents the JS file at http://cdn.rawgit.com/Teun/thenBy.js/248eb629/thenBy.min.js from being loaded. Can we avoid loading content from `cdn.rawgit.com`?

**Comment by michielbdejong** [comment]
Fixed, apart from https://github.com/interledger/connector.land/blob/mj-latest-updates/public/index.html#L21-L22 which is a script in the /vendor folder that goes ahead and connects to Google's font service to load the actual Montserrat font, so I don't really know how to fix that.

@vhpoet do you know how we can switch to an open source font that does not require fetching data from Google?
